"""Backend error codes — machine-readable identifiers for API errors."""

# ── Client errors (4xx equivalent) ────────────────────────────────────────
NOT_FOUND = "NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"
PERMISSION_DENIED = "PERMISSION_DENIED"

# ── CLI/Backend errors ────────────────────────────────────────────────────
CLI_ERROR = "CLI_ERROR"
CLI_TIMEOUT = "CLI_TIMEOUT"
WRITE_ERROR = "WRITE_ERROR"
EDIT_ERROR = "EDIT_ERROR"
LIST_ERROR = "LIST_ERROR"
READ_ERROR = "READ_ERROR"
SEARCH_ERROR = "SEARCH_ERROR"

# ── External service errors ───────────────────────────────────────────────
GEOCODE_ERROR = "GEOCODE_ERROR"

# ── Import errors (Tranche A) ─────────────────────────────────────────────
IMPORT_SOURCE_UNSUPPORTED = "IMPORT_SOURCE_UNSUPPORTED"
IMPORT_SOURCE_UNREADABLE = "IMPORT_SOURCE_UNREADABLE"
IMPORT_PLAN_SCHEMA_UNSUPPORTED = "IMPORT_PLAN_SCHEMA_UNSUPPORTED"
IMPORT_PLAN_INVALID = "IMPORT_PLAN_INVALID"
IMPORT_PLAN_CONFLICTS_UNRESOLVED = "IMPORT_PLAN_CONFLICTS_UNRESOLVED"
IMPORT_CONFIRMATION_REQUIRED = "IMPORT_CONFIRMATION_REQUIRED"
IMPORT_CONFLICT_EXISTING_PATH = "IMPORT_CONFLICT_EXISTING_PATH"
IMPORT_IDEMPOTENCY_CONFLICT = "IMPORT_IDEMPOTENCY_CONFLICT"
IMPORT_JOB_NOT_COMMITTED = "IMPORT_JOB_NOT_COMMITTED"
IMPORT_WRITE_FAILURE = "IMPORT_WRITE_FAILURE"
IMPORT_JOB_NOT_FOUND = "IMPORT_JOB_NOT_FOUND"
IMPORT_ROLLBACK_MANIFEST_MISSING = "IMPORT_ROLLBACK_MANIFEST_MISSING"
IMPORT_ROLLBACK_CHECKSUM_MISMATCH = "IMPORT_ROLLBACK_CHECKSUM_MISMATCH"
IMPORT_ROLLBACK_UNSAFE = "IMPORT_ROLLBACK_UNSAFE"
IMPORT_INTERNAL_ERROR = "IMPORT_INTERNAL_ERROR"

# ── Catch-all ─────────────────────────────────────────────────────────────
INTERNAL_ERROR = "INTERNAL_ERROR"
