"""Backend error codes — machine-readable identifiers for API errors."""

# ── Client errors (4xx equivalent) ────────────────────────────────────────
NOT_FOUND = "NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"
PERMISSION_DENIED = "PERMISSION_DENIED"

# ── CLI/Backend errors ────────────────────────────────────────────────────
CLI_ERROR = "CLI_ERROR"
CLI_TIMEOUT = "CLI_TIMEOUT"
WRITE_ERROR = "WRITE_ERROR"
EDIT_ERROR = "EDIT_ERROR"
LIST_ERROR = "LIST_ERROR"
READ_ERROR = "READ_ERROR"
SEARCH_ERROR = "SEARCH_ERROR"

# ── External service errors ───────────────────────────────────────────────
GEOCODE_ERROR = "GEOCODE_ERROR"

# ── Import errors (Tranche A) ─────────────────────────────────────────────
IMPORT_SOURCE_UNSUPPORTED = "IMPORT_SOURCE_UNSUPPORTED"
IMPORT_SOURCE_UNREADABLE = "IMPORT_SOURCE_UNREADABLE"
IMPORT_PLAN_SCHEMA_UNSUPPORTED = "IMPORT_PLAN_SCHEMA_UNSUPPORTED"
IMPORT_PLAN_INVALID = "IMPORT_PLAN_INVALID"
IMPORT_PLAN_CONFLICTS_UNRESOLVED = "IMPORT_PLAN_CONFLICTS_UNRESOLVED"
IMPORT_CONFIRMATION_REQUIRED = "IMPORT_CONFIRMATION_REQUIRED"
IMPORT_CONFLICT_EXISTING_PATH = "IMPORT_CONFLICT_EXISTING_PATH"
IMPORT_IDEMPOTENCY_CONFLICT = "IMPORT_IDEMPOTENCY_CONFLICT"
IMPORT_JOB_NOT_COMMITTED = "IMPORT_JOB_NOT_COMMITTED"
IMPORT_WRITE_FAILURE = "IMPORT_WRITE_FAILURE"
IMPORT_JOB_NOT_FOUND = "IMPORT_JOB_NOT_FOUND"
IMPORT_ROLLBACK_MANIFEST_MISSING = "IMPORT_ROLLBACK_MANIFEST_MISSING"
IMPORT_ROLLBACK_CHECKSUM_MISMATCH = "IMPORT_ROLLBACK_CHECKSUM_MISMATCH"
IMPORT_ROLLBACK_UNSAFE = "IMPORT_ROLLBACK_UNSAFE"
IMPORT_INTERNAL_ERROR = "IMPORT_INTERNAL_ERROR"

# ── M7 historical-photo review/batch authority codes (additive) ───────────
# All map 1:1 to the frozen CLI's own error codes (tools/ingest/review.py) so
# the CLI import job stays the sole durable authority; the backend only
# translates + strips unsafe recovery facts for the UI.
IMPORT_REVIEW_ALREADY_STAGED = "IMPORT_REVIEW_ALREADY_STAGED"
IMPORT_REVIEW_REVISION_CONFLICT = "IMPORT_REVIEW_REVISION_CONFLICT"
IMPORT_REVIEW_RECOVERY_REQUIRED = "IMPORT_REVIEW_RECOVERY_REQUIRED"
IMPORT_REVIEW_PROPOSAL_FROZEN = "IMPORT_REVIEW_PROPOSAL_FROZEN"
IMPORT_REVIEW_EDIT_INVALID = "IMPORT_REVIEW_EDIT_INVALID"
IMPORT_REVIEW_PLAN_MISSING = "IMPORT_REVIEW_PLAN_MISSING"
IMPORT_SOURCE_ROOT_UNREADABLE = "IMPORT_SOURCE_ROOT_UNREADABLE"
IMPORT_SOURCE_ROOT_IDENTITY_MISMATCH = "IMPORT_SOURCE_ROOT_IDENTITY_MISMATCH"
IMPORT_PREVIEW_UNAVAILABLE = "IMPORT_PREVIEW_UNAVAILABLE"
IMPORT_BATCH_ALREADY_ACTIVE = "IMPORT_BATCH_ALREADY_ACTIVE"
IMPORT_NO_RUNNABLE_PROPOSALS = "IMPORT_NO_RUNNABLE_PROPOSALS"
IMPORT_RECOVERY_REQUIRED = "IMPORT_RECOVERY_REQUIRED"
IMPORT_ROLLBACK_PARENT_NOT_ALLOWED = "IMPORT_ROLLBACK_PARENT_NOT_ALLOWED"
IMPORT_ROLLBACK_INTERRUPTED = "IMPORT_ROLLBACK_INTERRUPTED"

# Backend capability code for an argparse / no-such-command failure on the
# review/batch CLI surface (e.g. an installed CLI too old to know ``import
# validate``). One closed code — never IMPORT_REVIEW_UNAVAILABLE etc.
CLI_FEATURE_UNAVAILABLE = "CLI_FEATURE_UNAVAILABLE"

# ── Catch-all ─────────────────────────────────────────────────────────────
INTERNAL_ERROR = "INTERNAL_ERROR"
